//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace LargoSharedClasses.Localization {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class BaseControls {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseControls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("LargoSharedClasses.Localization.BaseControls", typeof(BaseControls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About program.
        /// </summary>
        public static string About_program {
            get {
                return ResourceManager.GetString("About program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add font.
        /// </summary>
        public static string Add_font {
            get {
                return ResourceManager.GetString("Add font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add line.
        /// </summary>
        public static string Add_line {
            get {
                return ResourceManager.GetString("Add line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tracks.
        /// </summary>
        public static string Add_tracks {
            get {
                return ResourceManager.GetString("Add tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added tracks.
        /// </summary>
        public static string Added_tracks {
            get {
                return ResourceManager.GetString("Added tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All in folder.
        /// </summary>
        public static string All_in_folder {
            get {
                return ResourceManager.GetString("All in folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All structures.
        /// </summary>
        public static string All_structures {
            get {
                return ResourceManager.GetString("All structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tracks.
        /// </summary>
        public static string All_tracks {
            get {
                return ResourceManager.GetString("All tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze after read.
        /// </summary>
        public static string Analyze_after_load {
            get {
                return ResourceManager.GetString("Analyze after load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing harmony....
        /// </summary>
        public static string Analyzing_harmony___ {
            get {
                return ResourceManager.GetString("Analyzing harmony...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing musical lines....
        /// </summary>
        public static string Analyzing_musical_lines___ {
            get {
                return ResourceManager.GetString("Analyzing musical lines...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange.
        /// </summary>
        public static string Arrange {
            get {
                return ResourceManager.GetString("Arrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement.
        /// </summary>
        public static string Arrangement {
            get {
                return ResourceManager.GetString("Arrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement type.
        /// </summary>
        public static string Arrangement_type {
            get {
                return ResourceManager.GetString("Arrangement type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As is.
        /// </summary>
        public static string As_is {
            get {
                return ResourceManager.GetString("As is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available discs.
        /// </summary>
        public static string Available_drivers {
            get {
                return ResourceManager.GetString("Available drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band.
        /// </summary>
        public static string Band {
            get {
                return ResourceManager.GetString("Band", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        public static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar horizontal inversion.
        /// </summary>
        public static string Bar_horizontal_inversion {
            get {
                return ResourceManager.GetString("Bar horizontal inversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars.
        /// </summary>
        public static string Bars {
            get {
                return ResourceManager.GetString("Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat.
        /// </summary>
        public static string Beat {
            get {
                return ResourceManager.GetString("Beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block model.
        /// </summary>
        public static string BlockModel {
            get {
                return ResourceManager.GetString("BlockModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        public static string Blocks {
            get {
                return ResourceManager.GetString("Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        public static string Blocks2 {
            get {
                return ResourceManager.GetString("Blocks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block-template.
        /// </summary>
        public static string BlockTemplate {
            get {
                return ResourceManager.GetString("BlockTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change of tracks.
        /// </summary>
        public static string Change_of_tracks {
            get {
                return ResourceManager.GetString("Change of tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change tones.
        /// </summary>
        public static string Change_tones {
            get {
                return ResourceManager.GetString("Change tones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for known notators.
        /// </summary>
        public static string Check_for_known_notators {
            get {
                return ResourceManager.GetString("Check for known notators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy line.
        /// </summary>
        public static string Clone_track {
            get {
                return ResourceManager.GetString("Clone line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common structures.
        /// </summary>
        public static string Common_structures {
            get {
                return ResourceManager.GetString("Common structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose.
        /// </summary>
        public static string Compose {
            get {
                return ResourceManager.GetString("Compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose all tracks.
        /// </summary>
        public static string Compose_all_tracks {
            get {
                return ResourceManager.GetString("Compose all tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composing....
        /// </summary>
        public static string Composing___ {
            get {
                return ResourceManager.GetString("Composing...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition.
        /// </summary>
        public static string Composition {
            get {
                return ResourceManager.GetString("Composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition of music.
        /// </summary>
        public static string Composition_of_music {
            get {
                return ResourceManager.GetString("Composition of music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consonance.
        /// </summary>
        public static string Consonance {
            get {
                return ResourceManager.GetString("Consonance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuity.
        /// </summary>
        public static string Continuity {
            get {
                return ResourceManager.GetString("Continuity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct octaves.
        /// </summary>
        public static string Correct_octaves {
            get {
                return ResourceManager.GetString("Correct octaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;Are you sure you want to delete this record?&apos;);.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine.
        /// </summary>
        public static string Determine {
            get {
                return ResourceManager.GetString("Determine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct melody.
        /// </summary>
        public static string Direct_melody {
            get {
                return ResourceManager.GetString("Direct melody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All from directory.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display score.
        /// </summary>
        public static string Display_score {
            get {
                return ResourceManager.GetString("Display score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide tones to halves.
        /// </summary>
        public static string Divide_tones_to_halves {
            get {
                return ResourceManager.GetString("Divide tones to halves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide tones to thirds.
        /// </summary>
        public static string Divide_tones_to_thirds {
            get {
                return ResourceManager.GetString("Divide tones to thirds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drift.
        /// </summary>
        public static string Drift {
            get {
                return ResourceManager.GetString("Drift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        public static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit program.
        /// </summary>
        public static string Exit_program {
            get {
                return ResourceManager.GetString("Exit program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting material....
        /// </summary>
        public static string Extracting_material___ {
            get {
                return ResourceManager.GetString("Extracting material...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting model....
        /// </summary>
        public static string Extracting_model___ {
            get {
                return ResourceManager.GetString("Extracting model...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth above.
        /// </summary>
        public static string Fifth_above {
            get {
                return ResourceManager.GetString("Fifth above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth below.
        /// </summary>
        public static string Fifth_below {
            get {
                return ResourceManager.GetString("Fifth below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No split.
        /// </summary>
        public static string FileSplit0 {
            get {
                return ResourceManager.GetString("FileSplit0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string FileSplit1 {
            get {
                return ResourceManager.GetString("FileSplit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total split.
        /// </summary>
        public static string FileSplit2 {
            get {
                return ResourceManager.GetString("FileSplit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-template.
        /// </summary>
        public static string FileTemplate {
            get {
                return ResourceManager.GetString("FileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling.
        /// </summary>
        public static string Filling {
            get {
                return ResourceManager.GetString("Filling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerboards of selected string instruments..
        /// </summary>
        public static string Fingerboards_of_selected_string_instruments_ {
            get {
                return ResourceManager.GetString("Fingerboards of selected string instruments.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerings.
        /// </summary>
        public static string Fingerings {
            get {
                return ResourceManager.GetString("Fingerings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished..
        /// </summary>
        public static string Finished_ {
            get {
                return ResourceManager.GetString("Finished.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Bar.
        /// </summary>
        public static string First_Bar {
            get {
                return ResourceManager.GetString("First Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From selected model.
        /// </summary>
        public static string From_selected_model {
            get {
                return ResourceManager.GetString("From selected model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        public static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic material.
        /// </summary>
        public static string Harmonic_material {
            get {
                return ResourceManager.GetString("Harmonic material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic material....
        /// </summary>
        public static string Harmonic_material___ {
            get {
                return ResourceManager.GetString("Harmonic material...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic motives.
        /// </summary>
        public static string Harmonic_motives {
            get {
                return ResourceManager.GetString("Harmonic motives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic order.
        /// </summary>
        public static string Harmonic_order {
            get {
                return ResourceManager.GetString("Harmonic order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic rhythm.
        /// </summary>
        public static string Harmonic_rhythm {
            get {
                return ResourceManager.GetString("Harmonic rhythm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic streams.
        /// </summary>
        public static string Harmonic_streams {
            get {
                return ResourceManager.GetString("Harmonic streams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic structures.
        /// </summary>
        public static string Harmonic_structures {
            get {
                return ResourceManager.GetString("Harmonic structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic system.
        /// </summary>
        public static string Harmonic_system {
            get {
                return ResourceManager.GetString("Harmonic system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic systems.
        /// </summary>
        public static string Harmonic_systems {
            get {
                return ResourceManager.GetString("Harmonic systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic motive.
        /// </summary>
        public static string HarmonicMotive {
            get {
                return ResourceManager.GetString("HarmonicMotive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonize parts.
        /// </summary>
        public static string Harmonize_score {
            get {
                return ResourceManager.GetString("Harmonize score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmony.
        /// </summary>
        public static string Harmony {
            get {
                return ResourceManager.GetString("Harmony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has template.
        /// </summary>
        public static string Has_template {
            get {
                return ResourceManager.GetString("Has template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest tone.
        /// </summary>
        public static string Highest_tone {
            get {
                return ResourceManager.GetString("Highest tone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight melodic voices.
        /// </summary>
        public static string Highlight_melodic_voices {
            get {
                return ResourceManager.GetString("Highlight melodic voices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulse.
        /// </summary>
        public static string Impulse {
            get {
                return ResourceManager.GetString("Impulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individualize melodic voices.
        /// </summary>
        public static string Individualize_melodic_voices {
            get {
                return ResourceManager.GetString("Individualize melodic voices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of components.
        /// </summary>
        public static string Initialization_of_components {
            get {
                return ResourceManager.GetString("Initialization of components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of data link.
        /// </summary>
        public static string Initialization_of_Data_Link {
            get {
                return ResourceManager.GetString("Initialization of Data Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of the player.
        /// </summary>
        public static string Initialization_of_the_player {
            get {
                return ResourceManager.GetString("Initialization of the player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted.
        /// </summary>
        public static string Inserted {
            get {
                return ResourceManager.GetString("Inserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed printers.
        /// </summary>
        public static string Installed_printers {
            get {
                return ResourceManager.GetString("Installed printers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument.
        /// </summary>
        public static string Instrument {
            get {
                return ResourceManager.GetString("Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument/channel.
        /// </summary>
        public static string Instrument_channel {
            get {
                return ResourceManager.GetString("Instrument/channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruments.
        /// </summary>
        public static string Instruments {
            get {
                return ResourceManager.GetString("Instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life.
        /// </summary>
        public static string Life {
            get {
                return ResourceManager.GetString("Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file.
        /// </summary>
        public static string Load_file {
            get {
                return ResourceManager.GetString("Load file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load into editor.
        /// </summary>
        public static string Load_into_editor {
            get {
                return ResourceManager.GetString("Load into editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load template.
        /// </summary>
        public static string Load_template {
            get {
                return ResourceManager.GetString("Load template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading model....
        /// </summary>
        public static string Loading_model___ {
            get {
                return ResourceManager.GetString("Loading model...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading primary key values.
        /// </summary>
        public static string Loading_primary_key_values {
            get {
                return ResourceManager.GetString("Loading primary key values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long tones.
        /// </summary>
        public static string Long_tones {
            get {
                return ResourceManager.GetString("Long tones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loudness.
        /// </summary>
        public static string Loudness {
            get {
                return ResourceManager.GetString("Loudness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest tone.
        /// </summary>
        public static string Lowest_tone {
            get {
                return ResourceManager.GetString("Lowest tone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main folder.
        /// </summary>
        public static string Main_folder {
            get {
                return ResourceManager.GetString("Main folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panels.
        /// </summary>
        public static string Main_panels {
            get {
                return ResourceManager.GetString("Main panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main setup.
        /// </summary>
        public static string Main_setup {
            get {
                return ResourceManager.GetString("Main setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean structures.
        /// </summary>
        public static string Mean_structures {
            get {
                return ResourceManager.GetString("Mean structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodic material.
        /// </summary>
        public static string Melodic_material {
            get {
                return ResourceManager.GetString("Melodic material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodic material....
        /// </summary>
        public static string Melodic_material___ {
            get {
                return ResourceManager.GetString("Melodic material...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodic motive.
        /// </summary>
        public static string Melodic_motive {
            get {
                return ResourceManager.GetString("Melodic motive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodic motive number.
        /// </summary>
        public static string Melodic_motive_number {
            get {
                return ResourceManager.GetString("Melodic motive number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodic motives.
        /// </summary>
        public static string Melodic_motives {
            get {
                return ResourceManager.GetString("Melodic motives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodic shape.
        /// </summary>
        public static string Melodic_shape {
            get {
                return ResourceManager.GetString("Melodic shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodic type.
        /// </summary>
        public static string Melodic_type {
            get {
                return ResourceManager.GetString("Melodic type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodic.
        /// </summary>
        public static string MelodicAdj {
            get {
                return ResourceManager.GetString("MelodicAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodic type.
        /// </summary>
        public static string MelodicFunction {
            get {
                return ResourceManager.GetString("MelodicFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodics.
        /// </summary>
        public static string Melodics {
            get {
                return ResourceManager.GetString("Melodics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodic structure.
        /// </summary>
        public static string MelodicStructure {
            get {
                return ResourceManager.GetString("MelodicStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metre.
        /// </summary>
        public static string Metre {
            get {
                return ResourceManager.GetString("Metre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        public static string Metric {
            get {
                return ResourceManager.GetString("Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi channel.
        /// </summary>
        public static string Midi_channel {
            get {
                return ResourceManager.GetString("Midi channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi devices.
        /// </summary>
        public static string Midi_devices {
            get {
                return ResourceManager.GetString("Midi devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI files.
        /// </summary>
        public static string MIDI_files {
            get {
                return ResourceManager.GetString("MIDI files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tones (MIDI).
        /// </summary>
        public static string Midi_tones {
            get {
                return ResourceManager.GetString("Midi tones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi line.
        /// </summary>
        public static string Midi_track {
            get {
                return ResourceManager.GetString("Midi line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string MidiChannel {
            get {
                return ResourceManager.GetString("MidiChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility.
        /// </summary>
        public static string Mobility {
            get {
                return ResourceManager.GetString("Mobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All models.
        /// </summary>
        public static string Model0 {
            get {
                return ResourceManager.GetString("Model0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original models.
        /// </summary>
        public static string Model1 {
            get {
                return ResourceManager.GetString("Model1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformed models.
        /// </summary>
        public static string Model2 {
            get {
                return ResourceManager.GetString("Model2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated models.
        /// </summary>
        public static string Model3 {
            get {
                return ResourceManager.GetString("Model3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembled models.
        /// </summary>
        public static string Model4 {
            get {
                return ResourceManager.GetString("Model4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modular deformation.
        /// </summary>
        public static string Modular_deformation {
            get {
                return ResourceManager.GetString("Modular deformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motive.
        /// </summary>
        public static string Motive {
            get {
                return ResourceManager.GetString("Motive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motives.
        /// </summary>
        public static string Motives {
            get {
                return ResourceManager.GetString("Motives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected files to folder.
        /// </summary>
        public static string Move_selected_files_to_folder {
            get {
                return ResourceManager.GetString("Move selected files to folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move line.
        /// </summary>
        public static string Move_track {
            get {
                return ResourceManager.GetString("Move line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string MP3Player0 {
            get {
                return ResourceManager.GetString("MP3Player0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default windows player.
        /// </summary>
        public static string MP3Player1 {
            get {
                return ResourceManager.GetString("MP3Player1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media control interface.
        /// </summary>
        public static string MP3Player2 {
            get {
                return ResourceManager.GetString("MP3Player2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal (media player).
        /// </summary>
        public static string MP3Player3 {
            get {
                return ResourceManager.GetString("MP3Player3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal (media element).
        /// </summary>
        public static string MP3Player4 {
            get {
                return ResourceManager.GetString("MP3Player4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multitasking.
        /// </summary>
        public static string Multitasking {
            get {
                return ResourceManager.GetString("Multitasking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest tone.
        /// </summary>
        public static string Music_player__mp3_ {
            get {
                return ResourceManager.GetString("Music player (mp3)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arranger.
        /// </summary>
        public static string Musical_arranger {
            get {
                return ResourceManager.GetString("Musical arranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical block.
        /// </summary>
        public static string Musical_block {
            get {
                return ResourceManager.GetString("Musical block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block model.
        /// </summary>
        public static string Musical_block_model {
            get {
                return ResourceManager.GetString("Musical block model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical blocks.
        /// </summary>
        public static string Musical_blocks {
            get {
                return ResourceManager.GetString("Musical blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical changes.
        /// </summary>
        public static string Musical_changes {
            get {
                return ResourceManager.GetString("Musical changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Musical_editor {
            get {
                return ResourceManager.GetString("Musical editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical file.
        /// </summary>
        public static string Musical_file {
            get {
                return ResourceManager.GetString("Musical file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File model.
        /// </summary>
        public static string Musical_file_model {
            get {
                return ResourceManager.GetString("Musical file model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation.
        /// </summary>
        public static string Musical_generation {
            get {
                return ResourceManager.GetString("Musical generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical instrument.
        /// </summary>
        public static string Musical_instrument {
            get {
                return ResourceManager.GetString("Musical instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervals.
        /// </summary>
        public static string Musical_intervals {
            get {
                return ResourceManager.GetString("Musical intervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical model.
        /// </summary>
        public static string Musical_model {
            get {
                return ResourceManager.GetString("Musical model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical rules.
        /// </summary>
        public static string Musical_rules {
            get {
                return ResourceManager.GetString("Musical rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical source.
        /// </summary>
        public static string Musical_source {
            get {
                return ResourceManager.GetString("Musical source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical structures.
        /// </summary>
        public static string Musical_structures {
            get {
                return ResourceManager.GetString("Musical structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical template.
        /// </summary>
        public static string Musical_template {
            get {
                return ResourceManager.GetString("Musical template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical templates.
        /// </summary>
        public static string Musical_templates {
            get {
                return ResourceManager.GetString("Musical templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tones.
        /// </summary>
        public static string Musical_tones {
            get {
                return ResourceManager.GetString("Musical tones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string MusicalTemplate {
            get {
                return ResourceManager.GetString("MusicalTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music-Mxl files.
        /// </summary>
        public static string MusicMxl_files {
            get {
                return ResourceManager.GetString("MusicMxl files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music-Xml files.
        /// </summary>
        public static string MusicXml_files {
            get {
                return ResourceManager.GetString("MusicXml files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutation.
        /// </summary>
        public static string Mutation {
            get {
                return ResourceManager.GetString("Mutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation.
        /// </summary>
        public static string Nation {
            get {
                return ResourceManager.GetString("Nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No line to compose.
        /// </summary>
        public static string No_track_to_compose {
            get {
                return ResourceManager.GetString("No line to compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notators.
        /// </summary>
        public static string Notators {
            get {
                return ResourceManager.GetString("Notators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bars.
        /// </summary>
        public static string Number_of_bars {
            get {
                return ResourceManager.GetString("Number of bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tones.
        /// </summary>
        public static string Number_of_tones {
            get {
                return ResourceManager.GetString("Number of tones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of lines.
        /// </summary>
        public static string Number_of_tracks {
            get {
                return ResourceManager.GetString("Number of lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurrence.
        /// </summary>
        public static string Occurrence {
            get {
                return ResourceManager.GetString("Occurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave.
        /// </summary>
        public static string Octave {
            get {
                return ResourceManager.GetString("Octave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave above.
        /// </summary>
        public static string Octave_above {
            get {
                return ResourceManager.GetString("Octave above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave below.
        /// </summary>
        public static string Octave_below {
            get {
                return ResourceManager.GetString("Octave below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave Down.
        /// </summary>
        public static string Octave_Down {
            get {
                return ResourceManager.GetString("Octave Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave number.
        /// </summary>
        public static string Octave_number {
            get {
                return ResourceManager.GetString("Octave number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave Up.
        /// </summary>
        public static string Octave_Up {
            get {
                return ResourceManager.GetString("Octave Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octaves.
        /// </summary>
        public static string Octaves {
            get {
                return ResourceManager.GetString("Octaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestrate.
        /// </summary>
        public static string Orchestrate {
            get {
                return ResourceManager.GetString("Orchestrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestration.
        /// </summary>
        public static string Orchestration {
            get {
                return ResourceManager.GetString("Orchestration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order_program {
            get {
                return ResourceManager.GetString("Order program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original division.
        /// </summary>
        public static string Original_division {
            get {
                return ResourceManager.GetString("Original division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file name.
        /// </summary>
        public static string Original_file_name {
            get {
                return ResourceManager.GetString("Original file name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original (loaded) tracks.
        /// </summary>
        public static string Original_tracks {
            get {
                return ResourceManager.GetString("Original tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model type.
        /// </summary>
        public static string OriginType {
            get {
                return ResourceManager.GetString("OriginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlines.
        /// </summary>
        public static string Outlines {
            get {
                return ResourceManager.GetString("Outlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panels.
        /// </summary>
        public static string Panels {
            get {
                return ResourceManager.GetString("Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters of engine.
        /// </summary>
        public static string Parameters_of_engine {
            get {
                return ResourceManager.GetString("Parameters of engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play mode.
        /// </summary>
        public static string Play_mode {
            get {
                return ResourceManager.GetString("Play mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play template.
        /// </summary>
        public static string Play_template {
            get {
                return ResourceManager.GetString("Play template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing file....
        /// </summary>
        public static string Preparing_file___ {
            get {
                return ResourceManager.GetString("Preparing file...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor speed.
        /// </summary>
        public static string Processor_speed {
            get {
                return ResourceManager.GetString("Processor speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare structures.
        /// </summary>
        public static string Rare_structures {
            get {
                return ResourceManager.GetString("Rare structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing primary keys.
        /// </summary>
        public static string Refreshing_primary_keys {
            get {
                return ResourceManager.GetString("Refreshing primary keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Register_program {
            get {
                return ResourceManager.GetString("Register program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular structures.
        /// </summary>
        public static string Regular_structures {
            get {
                return ResourceManager.GetString("Regular structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore layout.
        /// </summary>
        public static string Restore_layout {
            get {
                return ResourceManager.GetString("Restore layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result compositions.
        /// </summary>
        public static string Result_compositions {
            get {
                return ResourceManager.GetString("Result compositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythm.
        /// </summary>
        public static string Rhythm {
            get {
                return ResourceManager.GetString("Rhythm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic.
        /// </summary>
        public static string Rhythmic {
            get {
                return ResourceManager.GetString("Rhythmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic density.
        /// </summary>
        public static string Rhythmic_density {
            get {
                return ResourceManager.GetString("Rhythmic density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic material.
        /// </summary>
        public static string Rhythmic_material {
            get {
                return ResourceManager.GetString("Rhythmic material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic material....
        /// </summary>
        public static string Rhythmic_material___ {
            get {
                return ResourceManager.GetString("Rhythmic material...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic motive.
        /// </summary>
        public static string Rhythmic_motive {
            get {
                return ResourceManager.GetString("Rhythmic motive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic motive number.
        /// </summary>
        public static string Rhythmic_motive_number {
            get {
                return ResourceManager.GetString("Rhythmic motive number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic motives.
        /// </summary>
        public static string Rhythmic_motives {
            get {
                return ResourceManager.GetString("Rhythmic motives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic order.
        /// </summary>
        public static string Rhythmic_order {
            get {
                return ResourceManager.GetString("Rhythmic order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic structures.
        /// </summary>
        public static string Rhythmic_structures {
            get {
                return ResourceManager.GetString("Rhythmic structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic.
        /// </summary>
        public static string RhythmicAdj {
            get {
                return ResourceManager.GetString("RhythmicAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmics.
        /// </summary>
        public static string Rhythmics {
            get {
                return ResourceManager.GetString("Rhythmics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmic structure.
        /// </summary>
        public static string RhythmicStructure {
            get {
                return ResourceManager.GetString("RhythmicStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string Save_as {
            get {
                return ResourceManager.GetString("Save as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Save_changes {
            get {
                return ResourceManager.GetString("Save changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save layout.
        /// </summary>
        public static string Save_layout {
            get {
                return ResourceManager.GetString("Save layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        public static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        public static string Scores {
            get {
                return ResourceManager.GetString("Scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores and instrumentation....
        /// </summary>
        public static string Scores_and_instrumentation___ {
            get {
                return ResourceManager.GetString("Scores and instrumentation...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Select_all {
            get {
                return ResourceManager.GetString("Select all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select notator by hand.
        /// </summary>
        public static string Select_notator_by_hand {
            get {
                return ResourceManager.GetString("Select notator by hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected tracks.
        /// </summary>
        public static string Selected_tracks {
            get {
                return ResourceManager.GetString("Selected tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string SelectedShe {
            get {
                return ResourceManager.GetString("SelectedShe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection of tracks.
        /// </summary>
        public static string Selection_of_tracks {
            get {
                return ResourceManager.GetString("Selection of tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soundfonts.
        /// </summary>
        public static string Soundfonts {
            get {
                return ResourceManager.GetString("Soundfonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input files split.
        /// </summary>
        public static string Split_imported_files {
            get {
                return ResourceManager.GetString("Split imported files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures.
        /// </summary>
        public static string Structures {
            get {
                return ResourceManager.GetString("Structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System info.
        /// </summary>
        public static string System_info {
            get {
                return ResourceManager.GetString("System info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        public static string tbBlocks {
            get {
                return ResourceManager.GetString("tbBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string tbChanges {
            get {
                return ResourceManager.GetString("tbChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composers.
        /// </summary>
        public static string tbComposers {
            get {
                return ResourceManager.GetString("tbComposers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition.
        /// </summary>
        public static string tbComposition {
            get {
                return ResourceManager.GetString("tbComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string tbFiles {
            get {
                return ResourceManager.GetString("tbFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string tbInfo {
            get {
                return ResourceManager.GetString("tbInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string tbModels {
            get {
                return ResourceManager.GetString("tbModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motives.
        /// </summary>
        public static string tbMotives {
            get {
                return ResourceManager.GetString("tbMotives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestration.
        /// </summary>
        public static string tbOrchestration {
            get {
                return ResourceManager.GetString("tbOrchestration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performation.
        /// </summary>
        public static string tbPerformation {
            get {
                return ResourceManager.GetString("tbPerformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        public static string tbScores {
            get {
                return ResourceManager.GetString("tbScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string tbSources {
            get {
                return ResourceManager.GetString("tbSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        public static string tbTracks {
            get {
                return ResourceManager.GetString("tbTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation.
        /// </summary>
        public static string tbTransformation {
            get {
                return ResourceManager.GetString("tbTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tectonic.
        /// </summary>
        public static string Tectonic {
            get {
                return ResourceManager.GetString("Tectonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template part.
        /// </summary>
        public static string Template_part {
            get {
                return ResourceManager.GetString("Template part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template properties.
        /// </summary>
        public static string Template_properties {
            get {
                return ResourceManager.GetString("Template properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo.
        /// </summary>
        public static string Tempo {
            get {
                return ResourceManager.GetString("Tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tension.
        /// </summary>
        public static string Tension {
            get {
                return ResourceManager.GetString("Tension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone energy.
        /// </summary>
        public static string Tone_energy {
            get {
                return ResourceManager.GetString("Tone energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone pitch.
        /// </summary>
        public static string Tone_pitch {
            get {
                return ResourceManager.GetString("Tone pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tones.
        /// </summary>
        public static string Tones {
            get {
                return ResourceManager.GetString("Tones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total horizontal inversion.
        /// </summary>
        public static string Total_horizontal_inversion {
            get {
                return ResourceManager.GetString("Total horizontal inversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total vertical inversion.
        /// </summary>
        public static string Total_vertical_inversion {
            get {
                return ResourceManager.GetString("Total vertical inversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracer.
        /// </summary>
        public static string Tracer {
            get {
                return ResourceManager.GetString("Tracer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        public static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation.
        /// </summary>
        public static string Transformation {
            get {
                return ResourceManager.GetString("Transformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two octaves above.
        /// </summary>
        public static string Two_octaves_above {
            get {
                return ResourceManager.GetString("Two octaves above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two octaves below.
        /// </summary>
        public static string Two_octaves_below {
            get {
                return ResourceManager.GetString("Two octaves below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect.
        /// </summary>
        public static string Unselect {
            get {
                return ResourceManager.GetString("Unselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect all.
        /// </summary>
        public static string Unselect_all {
            get {
                return ResourceManager.GetString("Unselect all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variance.
        /// </summary>
        public static string Variance {
            get {
                return ResourceManager.GetString("Variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical extension.
        /// </summary>
        public static string Vertical_extension {
            get {
                return ResourceManager.GetString("Vertical extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical reduction.
        /// </summary>
        public static string Vertical_reduction {
            get {
                return ResourceManager.GetString("Vertical reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        public static string Voice {
            get {
                return ResourceManager.GetString("Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voices.
        /// </summary>
        public static string Voices {
            get {
                return ResourceManager.GetString("Voices", resourceCulture);
            }
        }
    }
}
