//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LargoSharedClasses.Localization {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LargoData.Localization.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to definition.
        /// </summary>
        internal static string BackToDef {
            get {
                return ResourceManager.GetString("BackToDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed records.
        /// </summary>
        internal static string DisplayedRecords {
            get {
                return ResourceManager.GetString("DisplayedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate music.
        /// </summary>
        internal static string GenerateMusic {
            get {
                return ResourceManager.GetString("GenerateMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --New block.
        /// </summary>
        internal static string MusNewBlock {
            get {
                return ResourceManager.GetString("MusNewBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --New composition.
        /// </summary>
        internal static string MusNewComposition {
            get {
                return ResourceManager.GetString("MusNewComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --New course.
        /// </summary>
        internal static string MusNewCourse {
            get {
                return ResourceManager.GetString("MusNewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --New engine.
        /// </summary>
        internal static string MusNewEngine {
            get {
                return ResourceManager.GetString("MusNewEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --New form.
        /// </summary>
        internal static string MusNewForm {
            get {
                return ResourceManager.GetString("MusNewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --New model.
        /// </summary>
        internal static string MusNewModel {
            get {
                return ResourceManager.GetString("MusNewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --New pattern.
        /// </summary>
        internal static string MusNewPattern {
            get {
                return ResourceManager.GetString("MusNewPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --New qualifier.
        /// </summary>
        internal static string MusNewQualifier {
            get {
                return ResourceManager.GetString("MusNewQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --New structure.
        /// </summary>
        internal static string MusNewStructure {
            get {
                return ResourceManager.GetString("MusNewStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New block.
        /// </summary>
        internal static string NewMusBlock {
            get {
                return ResourceManager.GetString("NewMusBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New composition.
        /// </summary>
        internal static string NewMusComposition {
            get {
                return ResourceManager.GetString("NewMusComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New content.
        /// </summary>
        internal static string NewMusContent {
            get {
                return ResourceManager.GetString("NewMusContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New course.
        /// </summary>
        internal static string NewMusCourse {
            get {
                return ResourceManager.GetString("NewMusCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New element.
        /// </summary>
        internal static string NewMusElement {
            get {
                return ResourceManager.GetString("NewMusElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New engine.
        /// </summary>
        internal static string NewMusEngine {
            get {
                return ResourceManager.GetString("NewMusEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New form.
        /// </summary>
        internal static string NewMusForm {
            get {
                return ResourceManager.GetString("NewMusForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New model.
        /// </summary>
        internal static string NewMusModel {
            get {
                return ResourceManager.GetString("NewMusModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New pattern.
        /// </summary>
        internal static string NewMusPattern {
            get {
                return ResourceManager.GetString("NewMusPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New phrase.
        /// </summary>
        internal static string NewMusPhrase {
            get {
                return ResourceManager.GetString("NewMusPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New qualifier.
        /// </summary>
        internal static string NewMusQualifier {
            get {
                return ResourceManager.GetString("NewMusQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New structure.
        /// </summary>
        internal static string NewMusStruct {
            get {
                return ResourceManager.GetString("NewMusStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open block.
        /// </summary>
        internal static string OpenMusBlock {
            get {
                return ResourceManager.GetString("OpenMusBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open model.
        /// </summary>
        internal static string OpenMusModel {
            get {
                return ResourceManager.GetString("OpenMusModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythmical system.
        /// </summary>
        internal static string RhytmicalSystem {
            get {
                return ResourceManager.GetString("RhytmicalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected record.
        /// </summary>
        internal static string SelectedRecord {
            get {
                return ResourceManager.GetString("SelectedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
    }
}
